services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: autoflex_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autoflex_db
      POSTGRES_USER: autoflex_user
      POSTGRES_PASSWORD: autoflex_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: